### ISSUE TITLE
Less rules in iptables by using -m multiport

### ISSUE THREAD

**Issue by sadeqn** [hbahadorzadeh/wit#2]
Using -m multiport can reduce the number of iptables rules.
`iptables -t nat -A PREROUTING -p tcp -m multiport --dports Port1,Port2,...,PortN -j REDIRECT --to-ports WIT_HTTPS_PORT`

**Comment by hbahadorzadeh** [comment]
It's solved by adding wit chain to iptables. I personally prefers to have one rule per port to have more control if i needed some customization.

**Comment by sadeqn** [comment]
But more iptables rule means more load on server.
